* THUmacs - Storing and updating deadlines for students of THU
** Quick Start
   Using this package is quite simple. Put the files under a local
   directory and add this directory to load path:

   : (add-to-list 'load-path "/path/to/your/directory")   
   
   Then add these lines to your emacs's initial file:
   
   : (setq dp-userid "Your user name")
   
   : (setq dp-userpass "Your password")

   : (setq dp-homework-file "/path/to/store/deadlines")

   Then you can use:

   : (dp-update-deadline-and-notify)

   And if you only want to write these deadlines to a file, use M-x
   dp-write-deadlines-to-file instead.

** For Org-mode users
   I prefer to put the dp-homework-file in the Org-mode's agenda file
   list.  This is very convenient to make use of the agenda view.  

   Personally, I also recommend to use [[https://github.com/kiwanami/emacs-calfw][calfw]] to present the deadlines
   which have been added to Org-mode's agenda in a calendar buffer.
   Calfw can interoperate with Org-mode very well.:)
